const { randomUUID } = require('crypto');

const towers = [
  {
    id: 'TWR-001',
    name: 'Bole District Tower 4',
    region: 'Addis Ababa',
    lat: 9.0222,
    lng: 38.7468,
    baseHourlyRevenue: 1200,
    currentAvailability: 100,
    voiceSuccessRate: 98.8,
    smsSuccessRate: 99.2,
    dataSuccessRate: 97.6,
    dataThroughputMbps: 84.1,
    voiceCallAttempts: 160,
    smsVolume: 420,
    dataSessions: 75,
    activeUsers: 1840,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-002',
    name: 'Merkato Sector Tower',
    region: 'Addis Ababa',
    lat: 9.0235,
    lng: 38.7480,
    baseHourlyRevenue: 900,
    currentAvailability: 100,
    voiceSuccessRate: 97.2,
    smsSuccessRate: 98.1,
    dataSuccessRate: 95.8,
    dataThroughputMbps: 72.4,
    voiceCallAttempts: 142,
    smsVolume: 530,
    dataSessions: 64,
    activeUsers: 1530,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-003',
    name: 'Bahir Dar Core Site',
    region: 'Bahir Dar',
    lat: 11.5936,
    lng: 37.3900,
    baseHourlyRevenue: 650,
    currentAvailability: 100,
    voiceSuccessRate: 99.4,
    smsSuccessRate: 99.0,
    dataSuccessRate: 98.9,
    dataThroughputMbps: 66.7,
    voiceCallAttempts: 110,
    smsVolume: 380,
    dataSessions: 48,
    activeUsers: 980,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-004',
    name: 'Hawassa Edge Site',
    region: 'Hawassa',
    lat: 7.0628,
    lng: 38.4760,
    baseHourlyRevenue: 780,
    currentAvailability: 100,
    voiceSuccessRate: 96.1,
    smsSuccessRate: 97.8,
    dataSuccessRate: 96.4,
    dataThroughputMbps: 58.9,
    voiceCallAttempts: 125,
    smsVolume: 405,
    dataSessions: 58,
    activeUsers: 1120,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-005',
    name: 'Jimma Gateway Tower',
    region: 'Jimma',
    lat: 7.6660,
    lng: 36.8330,
    baseHourlyRevenue: 520,
    currentAvailability: 100,
    voiceSuccessRate: 98.0,
    smsSuccessRate: 98.6,
    dataSuccessRate: 97.0,
    dataThroughputMbps: 61.2,
    voiceCallAttempts: 130,
    smsVolume: 410,
    dataSessions: 53,
    activeUsers: 870,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-006',
    name: 'Mekelle Central Tower',
    region: 'Mekelle',
    lat: 13.4967,
    lng: 39.4767,
    baseHourlyRevenue: 480,
    currentAvailability: 100,
    voiceSuccessRate: 97.5,
    smsSuccessRate: 98.0,
    dataSuccessRate: 96.8,
    dataThroughputMbps: 55.3,
    voiceCallAttempts: 95,
    smsVolume: 310,
    dataSessions: 42,
    activeUsers: 720,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-007',
    name: 'Gondar Heritage Tower',
    region: 'Gondar',
    lat: 12.6030,
    lng: 37.4521,
    baseHourlyRevenue: 410,
    currentAvailability: 100,
    voiceSuccessRate: 96.2,
    smsSuccessRate: 97.1,
    dataSuccessRate: 95.4,
    dataThroughputMbps: 48.7,
    voiceCallAttempts: 88,
    smsVolume: 275,
    dataSessions: 38,
    activeUsers: 650,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-008',
    name: 'Dessie North Tower',
    region: 'Dessie',
    lat: 11.1333,
    lng: 39.6333,
    baseHourlyRevenue: 380,
    currentAvailability: 100,
    voiceSuccessRate: 94.8,
    smsSuccessRate: 96.3,
    dataSuccessRate: 93.7,
    dataThroughputMbps: 44.2,
    voiceCallAttempts: 82,
    smsVolume: 255,
    dataSessions: 35,
    activeUsers: 590,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-009',
    name: 'Adama Industrial Site',
    region: 'Adama',
    lat: 8.5400,
    lng: 39.2700,
    baseHourlyRevenue: 560,
    currentAvailability: 100,
    voiceSuccessRate: 98.1,
    smsSuccessRate: 98.7,
    dataSuccessRate: 97.4,
    dataThroughputMbps: 63.8,
    voiceCallAttempts: 118,
    smsVolume: 370,
    dataSessions: 55,
    activeUsers: 890,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-010',
    name: 'Dire Dawa Logistics Tower',
    region: 'Dire Dawa',
    lat: 9.5931,
    lng: 41.8661,
    baseHourlyRevenue: 620,
    currentAvailability: 100,
    voiceSuccessRate: 97.8,
    smsSuccessRate: 98.4,
    dataSuccessRate: 96.9,
    dataThroughputMbps: 59.4,
    voiceCallAttempts: 105,
    smsVolume: 340,
    dataSessions: 47,
    activeUsers: 780,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-011',
    name: 'Harar Walled City Tower',
    region: 'Harar',
    lat: 9.3125,
    lng: 42.1198,
    baseHourlyRevenue: 290,
    currentAvailability: 100,
    voiceSuccessRate: 95.6,
    smsSuccessRate: 96.8,
    dataSuccessRate: 94.2,
    dataThroughputMbps: 38.6,
    voiceCallAttempts: 70,
    smsVolume: 215,
    dataSessions: 28,
    activeUsers: 420,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-012',
    name: 'Sodo Southern Tower',
    region: 'Sodo',
    lat: 6.8583,
    lng: 37.7583,
    baseHourlyRevenue: 320,
    currentAvailability: 100,
    voiceSuccessRate: 93.4,
    smsSuccessRate: 95.1,
    dataSuccessRate: 92.8,
    dataThroughputMbps: 36.4,
    voiceCallAttempts: 75,
    smsVolume: 230,
    dataSessions: 31,
    activeUsers: 480,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-013',
    name: 'Assosa Border Tower',
    region: 'Assosa',
    lat: 10.0667,
    lng: 34.5333,
    baseHourlyRevenue: 180,
    currentAvailability: 100,
    voiceSuccessRate: 91.2,
    smsSuccessRate: 93.4,
    dataSuccessRate: 89.7,
    dataThroughputMbps: 28.5,
    voiceCallAttempts: 55,
    smsVolume: 165,
    dataSessions: 19,
    activeUsers: 280,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-014',
    name: 'Gambela Wetlands Tower',
    region: 'Gambela',
    lat: 8.2524,
    lng: 34.5905,
    baseHourlyRevenue: 140,
    currentAvailability: 100,
    voiceSuccessRate: 88.5,
    smsSuccessRate: 91.2,
    dataSuccessRate: 86.3,
    dataThroughputMbps: 22.1,
    voiceCallAttempts: 45,
    smsVolume: 135,
    dataSessions: 15,
    activeUsers: 210,
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'TWR-015',
    name: 'Jijiga Eastern Hub',
    region: 'Jijiga',
    lat: 9.3500,
    lng: 42.7833,
    baseHourlyRevenue: 350,
    currentAvailability: 100,
    voiceSuccessRate: 94.1,
    smsSuccessRate: 95.8,
    dataSuccessRate: 93.3,
    dataThroughputMbps: 41.7,
    voiceCallAttempts: 80,
    smsVolume: 245,
    dataSessions: 33,
    activeUsers: 520,
    lastUpdated: new Date().toISOString()
  }
];

const failedTransactions = [];
const mpesaTransactions = [];
const agentInsights = [];

const banks = [
  { id: 'cbe',       name: 'CBE',       fullName: 'Commercial Bank of Ethiopia', successRate: 98.2, apiLatencyMs: 145, connected: true,  incidents: 0 },
  { id: 'coop',      name: 'Coop',      fullName: 'Cooperative Bank of Oromia',  successRate: 97.9, apiLatencyMs: 168, connected: true,  incidents: 0 },
  { id: 'awash',     name: 'Awash',     fullName: 'Awash Bank',                  successRate: 97.1, apiLatencyMs: 182, connected: true,  incidents: 0 },
  { id: 'dashen',    name: 'Dashen',    fullName: 'Dashen Bank',                 successRate: 96.8, apiLatencyMs: 210, connected: true,  incidents: 1 },
  { id: 'abyssinia', name: 'Abyssinia', fullName: 'Bank of Abyssinia',           successRate: 95.4, apiLatencyMs: 268, connected: true,  incidents: 0 },
  { id: 'wegagen',   name: 'Wegagen',   fullName: 'Wegagen Bank',                successRate: 94.2, apiLatencyMs: 315, connected: true,  incidents: 1 },
  { id: 'berhan',    name: 'Berhan',    fullName: 'Berhan Bank',                 successRate: 92.7, apiLatencyMs: 412, connected: false, incidents: 2 },
  { id: 'bunna',     name: 'Bunna',     fullName: 'Bunna International Bank',    successRate: 91.3, apiLatencyMs: 485, connected: true,  incidents: 1 },
];

function createId(prefix = 'id') {
  return `${prefix}-${randomUUID().slice(0, 8)}`;
}

module.exports = {
  towers,
  failedTransactions,
  mpesaTransactions,
  agentInsights,
  banks,
  createId
};
